import React from 'react';
import { BRASS, CREAM, FOREST, INK, LINE, MOSS, PAPER, SERIF, SANS } from '../components/clientTheme';

const photos = {
  hero: 'https://lawiswiskawayanresort.com/wp-content/uploads/2024/09/About-Lawiswis-Kawayan-scaled-1.jpeg',
  garden: 'https://lawiswiskawayanresort.com/wp-content/uploads/2024/10/Main-Villa-07.jpeg',
  pool: 'https://lawiswiskawayanresort.com/wp-content/uploads/2024/10/2017-16.jpg',
  dining: 'https://lawiswiskawayanresort.com/wp-content/uploads/2024/10/Hapag-04.jpeg',
};

const values = [
  ['01', 'Genuine hospitality', 'Every guest is welcomed with the warmth and care we would offer family.'],
  ['02', 'A love for nature', 'Our bamboo gardens are not decoration. They are the rhythm of the place.'],
  ['03', 'Room to reconnect', 'From quiet weekends to big reunions, every stay should leave space for memory.'],
];

export default function About() {
  return <div style={{ background: PAPER }}>
    <section style={{ minHeight: '540px', position: 'relative', display: 'flex', alignItems: 'end', padding: '70px 24px', overflow: 'hidden' }}><img src={photos.hero} alt="Lawiswis Kawayan garden" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' }} /><div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(90deg, rgba(20,25,15,.75), rgba(20,25,15,.15))' }} /><div style={{ position: 'relative', maxWidth: '1100px', width: '100%', margin: '0 auto' }}><div style={{ color: '#e7dfc4', font: `600 11px ${SANS}`, letterSpacing: '.16em', textTransform: 'uppercase', marginBottom: '14px' }}>Our story · Since 2006</div><h1 style={{ color: '#fff', font: `500 clamp(44px, 7vw, 78px)/1 ${SERIF}`, margin: '0 0 18px', maxWidth: '700px' }}>A garden shaped by love, memory, and bamboo.</h1><p style={{ color: 'rgba(255,255,255,.8)', font: `14px/1.8 ${SANS}`, maxWidth: '500px', margin: 0 }}>Lawiswis Kawayan is a peaceful hideaway in Calumpit, Bulacan, where the day slows down naturally.</p></div></section>
    <section style={{ maxWidth: '1100px', margin: '0 auto', padding: '100px 24px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '70px', alignItems: 'center' }}><img src={photos.garden} alt="Resort villa" style={{ width: '100%', height: '450px', objectFit: 'cover' }} /><div><div style={{ color: MOSS, font: `600 11px ${SANS}`, letterSpacing: '.16em', textTransform: 'uppercase', marginBottom: '14px' }}>The meaning of Lawiswis Kawayan</div><h2 style={{ color: INK, font: `500 40px/1.15 ${SERIF}`, margin: '0 0 20px' }}>A quiet place to return to yourself.</h2><p style={{ color: '#5c5a4c', font: `14px/1.9 ${SANS}`, marginBottom: '16px' }}>Our name comes from a cherished Filipino song taught by our founder's late father. Like the murmur of bamboo, the resort is meant to feel gentle, familiar, and alive.</p><p style={{ color: '#5c5a4c', font: `14px/1.9 ${SANS}`, margin: 0 }}>Since 2006, families, couples, corporate teams, and weekend travelers have found their own version of rest here. The garden keeps growing, but the welcome stays the same.</p></div></section>
    <section style={{ background: CREAM, padding: '90px 24px' }}><div style={{ maxWidth: '1100px', margin: '0 auto' }}><div style={{ color: BRASS, font: `600 11px ${SANS}`, letterSpacing: '.16em', textTransform: 'uppercase', marginBottom: '12px' }}>What guides us</div><h2 style={{ color: INK, font: `500 40px ${SERIF}`, margin: '0 0 40px' }}>A stay with substance.</h2><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1px', background: LINE }}>{values.map(value => <div key={value[0]} style={{ background: CREAM, padding: '30px 26px', minHeight: '180px' }}><div style={{ color: BRASS, font: `500 24px ${SERIF}`, marginBottom: '22px' }}>{value[0]}</div><h3 style={{ color: INK, font: `600 18px ${SERIF}`, margin: '0 0 10px' }}>{value[1]}</h3><p style={{ color: '#6b6a5c', font: `12px/1.8 ${SANS}`, margin: 0 }}>{value[2]}</p></div>)}</div></div></section>
    <section style={{ maxWidth: '1100px', margin: '0 auto', padding: '100px 24px' }}><div style={{ display: 'grid', gridTemplateColumns: '1.2fr .8fr', gap: '18px' }}><img src={photos.pool} alt="Resort pool" style={{ width: '100%', height: '300px', objectFit: 'cover' }} /><img src={photos.dining} alt="Resort dining" style={{ width: '100%', height: '300px', objectFit: 'cover' }} /></div><div style={{ marginTop: '46px', display: 'flex', justifyContent: 'space-between', gap: '20px', flexWrap: 'wrap', alignItems: 'center' }}><div><div style={{ color: MOSS, font: `600 11px ${SANS}`, letterSpacing: '.16em', textTransform: 'uppercase' }}>Come find your pace</div><h2 style={{ color: INK, font: `500 34px ${SERIF}`, margin: '10px 0 0' }}>Your next quiet morning is waiting.</h2></div><button onClick={() => { window.location.href = '/rooms'; }} style={{ background: FOREST, color: '#fff', border: 0, borderRadius: '3px', padding: '14px 24px', font: `600 11px ${SANS}`, letterSpacing: '.06em', cursor: 'pointer' }}>BROWSE ROOMS →</button></div></section>
    <style>{`@media (max-width: 700px) { section { grid-template-columns: 1fr !important; } }`}</style>
  </div>;
}